sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - '8.6'

install:
    - npm i

script:
#    - ls -ltr **
    - npm run test-headless

cache:
  directories:
    - node_modules

notifications:
    email:
        on_success: never
        on_failure: change
