sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  # sauce_connect: true
  jwt:
    secure: P8sk28mQJMOAOzQQWuX0ZlYQiCTzWn8oHkzvhxhbwmO5yO2D0BcGruMcyDILjecoch0Bkw9wWi2rcwitoF2wwrGD6puI1Rlxa9OPPh+qjYrFYT5K8y0UKvgEb7aTixNsk/Y+JVThdm1uY6E2tiyQWcRB7569QqOFA0UQkmZvzpeOAIJ3bO6zYrNyxvf6AXL/fN8fWR+LOlqTqMpLPm+joS1r8OUNVWeL+11XfznlY/M1cIT87uVVYQBTpbW1pW4aZ43YUqJf/rfUeEligDh/6MtXth5aJ54kQ9Kyp5ZhLAE+lMI4dDY6qTNGsoXG5vtcpST10ovFTaT0OS4SQ2yG8eS3e83osgLUWxc4JPlwbljl0i0fiv0TjnzQikRqSs86+MhbDUpEH90T1CYyX/lnE/slHimv5wiJMUaWb+um1dDaLFAtojlGWehsF8Q2pPI8XyxXwPB35vCKDO1uvoReqzpxfbSQZ5j5jGbB8cGc2qBAUHQbLW7SlfolrT63EOuScuYIVcGBUe3M7uNhT5Gw4ZOlj7UJD5kWIi3fAO19D5X+eFmzTIwPo4b7vdn/J8PzJKPhpBTujTDfWacUW9sFU5DNugMyL+znm7N7vFwlKJveaH9M87Qwtb+oxXzgDtWJqCHIGJD7QdGqsKNkzlfw+YkcLOTcfOTUr+P7011JbuY=
language: node_js
env:
  global:
  - secure: A15GeXo6/AUwxoqqZURcO91Q6XguDsD2lsZaQ4nrC9FEjZDEJMSy5tEVxftJBSIuYH6ZXTjTKZwuimBeJojjDGqCpC4URDwaPmLOO+WdPZqqD1H1EQRgniaxfCDzDOW9IohzoslpXO0v+F8EAeTzl5/p+21pHOjuaqMYXLlO8dvZfw/HDy5i7UoejzB4+wkgRfAPUCKwIpmzNOFgLPbwPbijDGHXd7txJEEkZCxmzpK+qyA3i9Hh7AvCsC3dJ+k9S9jOTuTSjachg3uAzUMlmSn2hKYCKl1JQlJ+xIF1omGxKDLXzD1q6e9UL3JlpSPgXN/tDq67TFO/DieLH5M+icxc0KSfKpsoqCP0AAQL1YqA/PYIiA5fZEOE/pZIMwOwYDtpwRn5w+QOPhYoLivQP+PM1XC5POp8DtkPzDlvP/+RUHlfFhNowaUrMEt2diS3/fsy2kSPiu4lMaQ2iJhrF1Y9JMUG7sRKp4YzigG6qCc6X/gQk70RksTytZIk9RqjlilScwe1bwIkSCqlj9wCfSSoj9Wu03ZF8fZjQFAXnVAygC8os8Z0QSJH9DDau2zuH8MtYL88HC2YP42AO1EWGoe+PqPHJJQuELmxLBMbIe6VjySJ2UGXwqx5fYab5mO0SwzC5UVldSo0Lp27WZZtUJ6/o0VkUF91TyH1ZHf4Zq0=
  - secure: B1YhAlLgHdiSr929WU8NcAcZ4zdm2hFohIasinK6B2SOBsOaGh5oCGilKOGq9tNnpWmzRkvv4RSHrVCZy30cDNoQ2XY6OzKw4my88e+1y96UiIQTCCIOM47Zf172U5jXD/ODe3gbuWG213Y9ZkYrJjsrOsr4Qwkd5mpSbGVE0bpnuixzJSzeiCoErWpEiV+VGZMYVA/3iB9tu8B3bCiJJV9a6AgtvZXjioEpl41lTDvkoauHkMlIGHiXNYZloHMvBK05u/Tso6O7dB2KnAkA1eHevPFKh8AgdaXaRzaw2LsLc8/XjWgZLRjZtHtORuyRVZ41qNpi8zRyQ7j8HzTRog3eWaaVZxw2jjI3jwHCaLQtml5ooszQcHgtlAVs/CSQJFGml17DLLwHAz5IeEIGVg+GA7ze954lm0MhGvAehk9Jn5tP1Aii6av8DippMtuyt5W/0d/bjdI4cw508gcMTzY+zzLyuho/BIXy/unwP3EXUK4oQgGKaDyhq7eE30T27uiMPOjpsWxpFKl/iC7l5NwLsvPKuoWSF2O6yc5SjRFxPJS/YWROCy6w4NxLBHM7HmQ5U+hI5WQ86RRlrtdEnCwpE9rh7+WtATLVULayW0WodKSfReHykKlHR89LiTViGVInyqpDap2rhvbfrTyVHRWeIBI1KZVfbFshRG43GOQ=
node_js:
- '8.9.1'
install:
- npm i
script:
- npm run test-headless
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: change
